title: "Meu Nome | Blog"
theme: minima
baseurl: "" # Mantenha vazio se estiver no seu-usuario.github.io
permalink: /articles/:title/
remote_theme: pages-themes/hacker@v0.2.0

# Isso garante que o Jekyll ignore pastas que não interessam
exclude:
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
